### ISSUE TITLE
[DK2] SD Card sync should work seamlessly

### ISSUE THREAD

**Issue by beastoin** [BasedHardware/omi#1077]
## Overview
DevKit 2 SD Card(SDC) Syncs should work seamlessly.

## Features
- Sync audio from SDC to phone
- Sync SDC audio from phone to the Backend, create new memory
- Delete SDC's audio from phone

## Examples
<img width="1186" alt="Screenshot 2024-10-25 at 15 51 12" src="https://github.com/user-attachments/assets/82ab87a5-9f38-40d9-9b09-f636a6c540ab">

## TODO
- [x] Support storage `sdcard` in WALs, with total seconds est.
- [x] Listing all WALs in Sync page
- [x] Delete a wal
- [x] Sync WALs storage `sdcard` to phone
- [x] Sync progress:
  - [x] Show loading indicator for syncing wal
  - [x] Show total progress
- [ ] ~~Default on for Local Sync Feature~~

## Future idea
- Play SDC's audio

--- 
https://github.com/user-attachments/assets/4be9255b-9dc6-431c-a954-bcfcb80b1502
  \- by Nik

**Comment by mdmohsin7** [comment]
Related #1075

**Comment by kevvz** [comment]
This is 2.0.2 firmware right? 2.0.2 shouldn't work until #994 goes through.

**Comment by beastoin** [comment]
@kevvz mannn, lmk what you are waiting for, anything to make v2 works prob. let me check your PR.

**Comment by beastoin** [comment]
The current implement of SD Card syncs is not that good. Let me use WALs.

**Comment by vincentkoc** [comment]
Following

**Comment by beastoin** [comment]
@vincentkoc man, you could join dev logs at https://discord.com/channels/1192313062041067520/1298578734017941555/1298578836899893300

**Comment by beastoin** [comment]
Ref for future idea: https://github.com/orgs/BasedHardware/projects/1/views/1?pane=issue&itemId=84886690
