### ISSUE TITLE
Support OTA Firmware Updates for Omi DevKit 2

### ISSUE THREAD

**Issue by beastoin** [BasedHardware/omi#1393]
Currently, OTA firmware updates only support Friend (DK1) and Openglass. 

Let's add support for Omi DevKit 2.

## Usages

- Create a new Github release:
  - Tag name:
    - For Omi Dev Kit 2: Omi_DK2_v2.0.5
    - For Omi Dev Kit 1: Friend_v1.0.4 or Omi_DK1_v1.0.4
    - For OpenGlass: OpenGlass_v1.0.4
  - Release note, including with the instruction:
    ```
    <!-- KEY_VALUE_START
    release_firmware_version:v2.0.5
    minimum_firmware_required:v2.0.0
    minimum_app_version:1.0.48
    minimum_app_version_code:181
    KEY_VALUE_END -->
     ```
- Build the firmware release:
  - `$adafruit-nrfutil dfu genpkg --dev-type 0x0052 --application zephyr.hex Omi_DK2_OTA_v2.0.5.zip`
  - ⚠️ Please note the file's name must contains `OTA`
 - Attach the `Omi_DK2_OTA_v2.0.5.zip` to the release

## Todos
- [x] API /firmware/latest add support Omi DevKit2
- [x] Mobile send device... to API /firmware/latest
- [x] Release with notes guidline

**Comment by beastoin** [comment]
<img width="856" alt="Screenshot 2024-11-23 at 13 19 12" src="https://github.com/user-attachments/assets/702f73a7-3b14-481a-881a-5f0bdbd26b99">

**Comment by beastoin** [comment]
<img width="607" alt="Screenshot 2024-11-23 at 13 19 44" src="https://github.com/user-attachments/assets/41ce4757-8f8a-41c1-a3af-14034a52291e">

**Comment by beastoin** [comment]
https://github.com/adafruit/Adafruit_nRF52_nrfutil

**Comment by francip** [comment]
DK2 runs the same bootloader as DK1, so the OTA support in DK1 should directly be useable for DK2.

**Comment by beastoin** [comment]
```
$ curl -X 'GET' \
  'https://backend-dt5lrfkkoa-uc.a.run.app/v2/firmware/latest?device_model=Omi%20DevKit%202&firmware_revision=asdsad&hardware_revision=asdasd&manufacturer_name=asdasdasd' \
  -H 'accept: application/json'
{"version":"v2.0.5","min_version":"v2.0.0","min_app_version":"1.0.48","min_app_version_code":"181","zip_url":"https://github.com/BasedHardware/omi/releases/download/Omi_DK2_v2.0.5/Omi_DK2_OTA_v2.0.5.zip"}%
```

**Comment by beastoin** [comment]
`$adafruit-nrfutil dfu genpkg --dev-type 0x0052 --application zephyr.hex dfu-package.zip`

**Comment by beastoin** [comment]
```
<!-- KEY_VALUE_START
release_firmware_version:v2.0.5
minimum_firmware_required:v2.0.0
minimum_app_version:1.0.48
minimum_app_version_code:181
KEY_VALUE_END -->
```

**Comment by beastoin** [comment]
<img width="500" alt="Screenshot 2024-12-01 at 17 41 01" src="https://github.com/user-attachments/assets/fac82022-064e-4d1b-b009-dcba6325b6e0">

<img width="500" alt="Screenshot 2024-12-01 at 17 43 09" src="https://github.com/user-attachments/assets/b69b1614-5ce4-4028-9db5-a1c844ba4cbc">
