### ISSUE TITLE
Let devs charge for apps

### ISSUE THREAD

**Issue by beastoin** [BasedHardware/omi#1404]
we need to let devs charge money from apps 

ideally to finish it by friday 29th this week so that we could announce it on 30th

Developer needs to specify if the app is:
- free
- paid

If paid, using stripe connect devs need to specify the price for app. I think for now it should be recurring only (to simplify)
let's say $2/month or $5/months etc... 

I think this feature should be done  either
- via webview in mobile app so that appstore will not be able to charge 30%
- over-the-air updates so that appstore couldn't decline us because of it

in the future, we will need to build a device with our own screens so that we wouldn't depend on stores' rules

---
**Status:** releasing

**Todos:**  
1. [x] Create a Stripe account.  
2. [x] **App:** Add the paid/free and `$ per month` configuration to the app creator page.  
3. [x] **App:** Display `$ per month` instead of "Install App".  
4. [x] **App:** Show `$ per month` in the app list.  
5. [x] **App:** Navigate to the Stripe payment link to make a payment. Automatically check the payment status every 3-5 seconds, only when the user clicks the Stripe link (`$/month`).  
6. [x] **Backend:** Create an app with the paid/free plan, and create Stripe plans accordingly.  
7. [x] **Backend:** Respond with the plan, `$ per month`, and payment link in the apps endpoint.  
8. [x] **Backend:** Process Stripe payment subscriptions on success or failure, adding or removing the user’s subscription to the app.  
9. [x] **Backend:** Validate the plan when enable (install) the app ~~Validate the plan when plugins are used in chat, memory, or integrations.~~

**Deploy steps:**
- [x] Merge https://github.com/BasedHardware/omi/pull/1514
- [x] Merge https://github.com/BasedHardware/omi/pull/1513
- [x] Add env var: `STRIPE_API_KEY` `STRIPE_WEBHOOK_SECRET` to backend service
- [x] Deploy backend
- [x] Deploy app

**Refs**:
- proposal: https://github.com/BasedHardware/omi/issues/1404#issuecomment-2530167582

**Comment by beastoin** [comment]
@mdmohsin7 wanna take this ? i'll assist with the infra-related things just lmk your proposal.

**Comment by kodjima33** [comment]
This need to be done today as we'll announce it tmrw

**Comment by beastoin** [comment]
sry @mdmohsin7 let me 🌚

**Comment by beastoin** [comment]
## Proposal

**Omi holds the money**  

**Flow:**  
1. The app developer creates an app, sets it as a paid app, and enters the recurring amount ($/month). The Omi system will create a default payment plan: `plan_m1`.  
2. The user visits the app page and sees the `paid` label with the recurring price ($/month). The button should display `$2/month` instead of "Install App".  
3. The user clicks the install button, which navigates to the Stripe Connect page for payment. To simplify the process, the app should check the payment status every 3 seconds.  
4. Once the user has paid, a callback is triggered to the Omi system to confirm the payment. Omi will save the key `app:<id>:plan_m1:<user_id>` in Redis for one month. A transaction should also be added to Firestore under `plugin_data > :app_id > transactions{}`.  
5. App usage should validate the user's payment status before allowing access.  
6. Handle recurring payments via callbacks from the Omi system.

**Minor flow:**  
1. The app developer updates their app plan from free to paid or vice versa.  
2. The app developer updates the monthly subscription amount ($/month).  

**Todos:**  
1. Create a Stripe account.  
2. **App:** Add the paid/free and `$ per month` configuration to the app creator page.  
3. **App:** Display `$ per month` instead of "Install App".  
4. **App:** Show `$ per month` in the app list.  
5. **App:** Navigate to the Stripe payment link to make a payment. Automatically check the payment status every 3-5 seconds, only when the user clicks the Stripe link (`$/month`).  
6. **Backend:** Create an app with the paid/free plan, and create Stripe plans accordingly.  
7. **Backend:** Respond with the plan, `$ per month`, and payment link in the apps endpoint.  
8. **Backend:** Process Stripe payment subscriptions on success or failure, adding or removing the user’s subscription to the app.  
9. **Backend:** Validate the plan when plugins are used in chat, memory, or integrations.

**Comment by beastoin** [comment]
@mdmohsin7 could you help on the **App** side (check the Todos above) ? once the back-end work is complete, i'll get back to you, so pls move fast and ama 🌚

**Comment by mdmohsin7** [comment]
Sure @beastoin

**Comment by beastoin** [comment]
https://buy.stripe.com/8wM7wt15ycWVa0ocMV?client_reference_id=omi_uid_asdAD234234

**Comment by mdmohsin7** [comment]
2/ Adding three fields `is_paid`, `price`, `payment_type`. The `payment_type` will be `recurring` (monthly) or `one-time`

**Comment by beastoin** [comment]
5/ the field will be `payment_link`

**Comment by mdmohsin7** [comment]
Update to 2/: `payment_type ` is changed to `payment_plan`, and it will have values like `monthly_recurring`, `one_time` etc etc

PR with 2, 3, 4 dropping in a few minutes

**Comment by mdmohsin7** [comment]
Will do 5 once I have the `payment_link` to test

**Comment by beastoin** [comment]
## product change logs
1. feature on prod 🚀

@kodjima33 @mdmohsin7 congr ~
