### ISSUE TITLE
Make Chat Great Again

### ISSUE THREAD

**Issue by kodjima33** [BasedHardware/omi#1414]
**Describe the bug**

- [x] 1. When I asked for chat recommendation, it gave me some stupid reply saying "i don't recall any conversations". See screenshot. It should actually help me. 1.1 another stupid reply see screenshot  **done with bugs**
  - [x] `bug` It worked initially for 1-2 messages and then it stopped making sense. If I ask for something, it finds completely unrelated memories for it https://github.com/BasedHardware/omi/issues/1414#issuecomment-2519648940  -> #1539
  - [x] `bug` When I ask it for something (that is there in a memory), it continues with the previous message context, it does not respond to what I am asking at all (see screenshot) https://github.com/BasedHardware/omi/issues/1414#issuecomment-2519648940 -> #1539 
  - [x] `enhancement` chat suggests the irrelevant tools https://github.com/BasedHardware/omi/issues/1414#issuecomment-2525342534
  - [x] `bug` Apps respond correctly but with unrelated memories https://github.com/BasedHardware/omi/issues/1414#issuecomment-2519648940 -> #1539
  - [x] `bug` Apps respond correctly but also includes memories even when they are not needed https://github.com/BasedHardware/omi/issues/1414#issuecomment-2519648940 -> #1539

- [x] 2. in chatbox, instead of "ask friend anything" should be just "Message" 

- [x] 3. I think it's time we divide  chats. Let's make every chat with every app - separate. Not sure it's the best idea so if you'd have better proposals, lmk
  - [x] `bug` Apps send two initial messages instead of one
  - [x] `bug` There are no user sent messages for the omi app if I close and open the main app

- [ ] 4. Need an ability to pass files/images. Every other AI chat can do it and it's cringe we still don't allow this https://github.com/orgs/BasedHardware/projects/1/views/1?pane=issue&itemId=89418517

- [x] 5. Default chat should be with "omi" and always should be the priority. It's like 90% of users who chat with chatgpt default and not with apps.  #1497 

- [x] 6. Chat needs to remember the last app/persona i chatted with and open it. When user opens notification, make sure we open the correct chat  #1497
  - [x] `not work` When user opens notification, make sure we open the correct chat

- [x] 7. When typing a question/message, the cat window needs to expand vertically. (if there is new line). Currently it doesn't expand vertically

- [x] 8. EVERY MESSAGE in chat should be copyable. Even the message the user has sent. Now - not copyable. Pls fix it

**Screenshots**
![Clipboard 25 Nov 2024 at 18 57](https://github.com/user-attachments/assets/4594e033-fa72-40eb-94f4-ee7b8e6bfb9a)
![image](https://github.com/user-attachments/assets/0fce84e4-e065-4b78-a697-4d04d49b6eae)

**user ID (can we access the user info to validate the bug?):**

--
refs:
 - the previous checks https://github.com/BasedHardware/omi/issues/1414#issuecomment-2525333187

**Comment by josancamon19** [comment]
@kodjima33 
- (1) You mean that even if you don't have conversations related, it should provide a recommendation, right, based on your facts for example.
- (4) Can you explain how do you give images/files, like what the chat would do with it, 1  example with each would help better understand this
- (6) Not sure if I got it, you mean, that when you open the app, is not keeping track of the "plugin/app" used? Prob not, just tested this and it's working. 

I think I got it, so you mean 3) 6) are related, so if we make each app to be an independent page, notifications should open accordingly, right?

**Comment by kodjima33** [comment]
1. Yes
4. Look how I interact with advisor when need help - send a file and ask question ![image](https://github.com/user-attachments/assets/5e98bd02-8e92-4eae-9a8a-0b34b2fdd888)

**Comment by josancamon19** [comment]
@kodjima33 please test 1, 1.1 with your uid and questions you'd like

https://share.cleanshot.com/Pr4q2Klc

**Comment by josancamon19** [comment]
@kodjima33 can we move (4) to another ticket, I feel like that's a separate project on it's own, so should be treated independently, also this are my thoughts on the implementation
![Image](https://github.com/user-attachments/assets/b470c1c5-d152-4849-9c14-7c5c245e3367)

**Comment by josancamon19** [comment]
3) done, requires pushing the app first, otherwise if pushing the backend at the same time, otherwise chat plugins will not work.

**Comment by beastoin** [comment]
oops, anyway to make it backward compatible bro? or we have to wait for 70-100% current users update the new app.

**Comment by josancamon19** [comment]
yea done

**Comment by josancamon19** [comment]
But I cleared up all messages

**Comment by josancamon19** [comment]
Moved 4 to here https://github.com/orgs/BasedHardware/projects/1/views/1?pane=issue&itemId=89418517

**Comment by beastoin** [comment]
bro @josancamon19 , did your merge all checked items to the main branch ?
(screenshot)


![Image](https://github.com/user-attachments/assets/68790afd-2303-4e5a-a6b5-1c3c3d572e74)

**Comment by beastoin** [comment]
@mdmohsin7 hey man pls help me a bit with this ticket, use the current app version 1.0.48 (183) and play with it to verify if the above checked items are ready on current build or not.

**Comment by mdmohsin7** [comment]
Sure @beastoin let me

**Comment by mdmohsin7** [comment]
> When I asked for chat recommendation, it gave me some stupid reply saying "i don't recall any conversations". See screenshot. It should actually help me

- [ ] It worked initially for 1-2 messages and then it stopped making sense. If I ask for something, it finds completely unrelated memories for it
<img src="https://github.com/user-attachments/assets/33f27577-69ff-40eb-b6d5-51d63b29a1e9" height="600">

- [ ] When I ask it for something (that is there in a memory), it continues with the previous message context, it does not respond to what I am asking at all (see screenshot)
<img src="https://github.com/user-attachments/assets/4ac33eeb-6883-4a42-89ec-6c2da2de3653" height="600">


> I think it's time we divide chats. Let's make every chat with every app - separate. Not sure it's the best idea so if you'd have better proposals, lmk

- [ ] Apps respond correctly but with unrelated memories
<img src="https://github.com/user-attachments/assets/7a7dd2c7-b782-4311-b4ed-cbcb5a60c31f" height="600">

- [ ] Apps respond correctly but also includes memories even when they are not needed
<img src="https://github.com/user-attachments/assets/6a6f4ced-804c-4e91-a71b-be21bdc0a180" height="600">

- [x] Apps send two initial messages instead of one
<img src="https://github.com/user-attachments/assets/5f061351-94f7-488e-90f9-a3e91675f8be" height="600">

- [x] There are no user sent messages for the omi app if I close and open the main app

https://github.com/user-attachments/assets/32810848-dae4-4f2c-b6bd-c57da8f4f9dc

**Comment by mdmohsin7** [comment]
The checked items are there in the app but are not fully functional or good enough to be used everyday

**Comment by beastoin** [comment]
feel free to pick one, take this serious.

complete it with your best then lmk.

@mdmohsin7 good luck 🚀

**Comment by beastoin** [comment]
by Joan

---
- [x] 1. When I asked for chat recommendation, it gave me some stupid reply saying "i don't recall any conversations". See screenshot. It should actually help me

- [x] 1.1 another stupid reply see screenshot 

- [x] 3. I think it's time we divide  chats. Let's make every chat with every app - separate. Not sure it's the best idea so if you'd have better proposals, lmk
- [ ] 4. ~Need an ability to pass files/images. Every other AI chat can do it and it's cringe we still don't allow this~ Moved to it's own ticket
- [ ] 6. Chat needs to remember the last app/persona i chatted with and open it. When user opens notification, make sure we open the correct chat
- [x] 2. in chatbox, instead of "ask friend anything" should be just "Message" 
- [x] 5. Default chat should be with "omi" and always should be the priority. It's like 90% of users who chat with chatgpt default and not with apps. 
- [x] When typing a question/message, the cat window needs to expand vertically. (if there is new line). Currently it doesn't expand vertically
- [x] EVERY MESSAGE in chat should be copyable. Even the message the user has sent. Now - not copyable. Pls fix it

**Comment by beastoin** [comment]
progress updates

(screenshot)

![Image](https://github.com/user-attachments/assets/1747d12b-e13d-4c86-bd64-761d7112bac8)

**Comment by beastoin** [comment]
chat suggests the irrelevant tools https://discord.com/channels/1192313062041067520/1196485046249476187/1314135967019302944

![Image](https://github.com/user-attachments/assets/b9827acf-d736-4618-ae66-3ceefd1a139f)

**Comment by beastoin** [comment]
add chat button to the app page 

![Image](https://github.com/user-attachments/assets/1cc3462c-77e7-4e75-baa3-15da369fda95)

**Comment by beastoin** [comment]
progress updates

(screenshot)

![Image](https://github.com/user-attachments/assets/bff6e0f1-782a-4998-b618-7fe0eba22567)

**Comment by beastoin** [comment]
https://x.com/tunahorse21/status/1864358186909683937

**Comment by beastoin** [comment]
@gaulucky92

**Comment by beastoin** [comment]
progress updates
(screenshot)

<img width="804" alt="Screenshot 2024-12-14 at 11 52 56" src="https://github.com/user-attachments/assets/8f88f9cc-a84e-4437-87d0-b3ebee92a91a" />

**Comment by beastoin** [comment]
progress updates
(screenshot)

<img width="790" alt="Image" src="https://github.com/user-attachments/assets/f7b12079-3c01-4936-a761-3e6bf198cc9a" />

**Comment by beastoin** [comment]
the remaining task will be updated at #1573

**Comment by beastoin** [comment]
![Image](https://github.com/user-attachments/assets/44094e1b-cfa8-47b1-9b38-f8b842d52c6d)
![Image](https://github.com/user-attachments/assets/9abd53bc-8cfb-40f8-9a97-6d50c8fbc323)
